apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-devops-sa
  labels:
    app: api-devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-devops-scaler
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-devops-sa-binding
subjects:
  - kind: ServiceAccount
    name: api-devops-sa
roleRef:
  kind: Role
  name: api-devops-scaler
  apiGroup: rbac.authorization.k8s.io